version: '3.1'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_USER: "${DB_APP_USER}"
            MYSQL_PASSWORD: "${DB_APP_PASSWORD}"
