version: '3.2'
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_APP_DATABASE}"
            MYSQL_USER: "${DB_APP_USER}"
            MYSQL_PASSWORD: "${DB_APP_PASSWORD}"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        environment:
            FLASK_APP: /scores
            FLASK_ENV: development
        ports:
            - 5000:5000
        volumes:
            - ./scores:/scores

volumes:
    dbdata:
